version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
