# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Logspout addon
version: "1.6.2"
image: "ghcr.io/bertbaron/{arch}-addon-logspout"
slug: logspout
description: "Send HA logging to remote log management systems"
url: "https://github.com/bertbaron/hassio-addons/tree/main/logspout"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: system
advanced: true
docker_api: true

map:
  - config

options:
  routes:
    - gelf://graylog.home:12201
  env: []
schema:
  routes:
    - str?
  hostname: str?
  env:
    - name: str
      value: str
