# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Logspout addon
version: "1.1.0"
image: "ghcr.io/bertbaron/{arch}-addon-logspout"
slug: logspout
description: "Send HA logging to a remote log management systems."
url: "https://github.com/bertbaron/hassio-addons/tree/main/logspout"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: system
advanced: true
docker_api: true

options:
  routes:
    - gelf://graylog.local:12201
  env:
    - name: SYSLOG_HOSTNAME
      value: homeassistant
    - name: INACTIVITY_TIMEOUT
      value: 1m
schema:
  routes:
    - str
  env:
    - name: str
      value: str
