# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
# Edge build: version is auto-bumped to the short git SHA by the CI workflow
name: Logspout (edge)
version: "29f87757"
image: "ghcr.io/bertbaron/logspout"
slug: logspout
description: "Send HA logging to remote log management systems"
url: "https://github.com/bertbaron/hassio-addons/tree/main/logspout"
arch:
  - aarch64
  - amd64
init: false
startup: system
advanced: true
docker_api: true

map:
  - config

options:
  routes:
    - gelf://graylog.home:12201
  hostname: homeassistant
  strip_ansi: false
  env: []
schema:
  routes:
    - str?
  hostname: str?
  strip_ansi: bool?
  env:
    - name: str
      value: str
