# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
# Edge build: version is auto-bumped to the short git SHA by the CI workflow
name: Logspout (test)
version: "452d5e1"
image: "ghcr.io/bertbaron/logspout"
slug: logspout
description: "Send HA logging to remote log management systems"
url: "https://github.com/bertbaron/hassio-addons/tree/main/logspout"
arch:
  - aarch64
  - amd64
init: false
startup: system
docker_api: true
journald: true
ingress: true
ingress_port: 8099
panel_icon: mdi:filter-variant
panel_title: Logspout
panel_admin: true

map:
  - type: homeassistant_config
  - type: addon_config
    read_only: false

options:
  routes:
    - gelf://graylog.home:12201
  hostname: homeassistant
  strip_ansi: false
  env: []
schema:
  routes:
    - str?
  hostname: str?
  strip_ansi: bool?
  env:
    - name: str
      value: str
  default_rules: list(off|latest|v1)?
  exclude_containers:
    - str?
