name: Builder

env:
  MONITORED_FILES: ".dockerignore config.yaml Dockerfile"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v6.0.2

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v47

      - name: Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
           if [[ "${{ steps.changed_files.outputs.all_changed_files }}" =~ $addon ]]; then
             for file in ${{ env.MONITORED_FILES }}; do
                 if [[ "${{ steps.changed_files.outputs.all_changed_files }}" =~ $addon/$file ]]; then
                   if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                     changed_addons+=("\"${addon}\",");
                   fi
                 fi
             done
           fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)

          if [[ -n ${changed} ]]; then
           echo "Changed add-ons: $changed";
           echo "changed=true" >> $GITHUB_OUTPUT;
           echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
           echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  build:
    needs: init
    if: needs.init.outputs.changed == 'true'
    name: Build ${{ matrix.addon }} add-on
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
    uses: ./.github/workflows/build-addon.yaml
    with:
      addon: ${{ matrix.addon }}
      publish: ${{ github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'develop') }}
    secrets: inherit
    permissions:
      contents: write
      id-token: write
      packages: write
